### ISSUE TITLE
¿Se puede saber si un CFDI está cancelado?

### ISSUE THREAD

**Issue by gmizaelmtzhdz** [phpcfdi/credentials#13]
Hola, 
Tengo una duda con el Webservice del SAT ¿se puede saber si un CFDI está cancelado?, hasta ahorita la única solución que le he encontrado es una combinación: 

-  Webservice del SAT para la extracción masiva de los CFDI's vigentes
- Web Scraping para obtener las canceladas (semi-automatizada ya que requiere la captura del captcha)

¿Habrá alguna otra forma automatizada de saber si los CFDI's están cancelados?

**Comment by eclipxe13** [comment]
Mira el proyecto [phpcfdi/sat-estado-cfdi](https://github.com/phpcfdi/sat-estado-cfdi)
Lee bien la documentación ;)
