### ISSUE TITLE
CADENA FIRMA ELECTRÓNICA.

### ISSUE THREAD

**Issue by Daniel-Monroy** [phpcfdi/credentials#14]
Estimado @eclipxe13, Estoy en un dilema. Necesito firmar un documento con mi E.Firma y poner el hash arrojado por el método 
`$certificado->publicKey()->publicKeyContents())`,  ¿Sabes si esto es lo correcto?.

Agradezco mucho tu apoyo.
Saludos.

**Comment by eclipxe13** [comment]
No es correcto.

Nota: Este tema se aclaró en el servidor de discord, en algún momento haré una serie de artículos al respecto.

Resumen:

- Con la e-firma o con un CSD se puede firmar cualquier cadena de bytes.
- Con la llave privada se puede firmar, y comprobar la firma con la llave pública (que está disponible en el certificado). Se puede firmar y verificar con los métodos `sign` y `verify`.
- Con la llave pública (que está disponible en el certificado) se puede firmar, y comprobar la firma con la llave privada. No implementado.
- No tiene ningún sentido firmar algo que no se pueda verificar.

El tema en específico tenía que ver con firmar un PDF. Pero, incluir la firma en el mismo archivo.
Esto genera el problema de que, al firmar el hash del archivo PDF, cuando se modifica para agregar la información de firma, cambia el origen de los datos de forma tal que no es posible realizar posteriormente la verificación.
Se podría hacer el firmado, pero no incluirlo en el mismo archivo, el archivo que produjo la firma debería almacenarse en un estado tal que sea inmutable.
Se podría usar la especificación de PDF para firmado de documentos, no parece sencillo implementarlo, pero tiene el problema de que las e-firma y CSD no tienen un servicio público estándar de recuperación de llaves públicas.
