### ISSUE TITLE
feat: soporte para crear pfx desde el certificado y la llave primaria

### ISSUE THREAD

**Issue by celli33** [phpcfdi/credentials#15]
Algunos Pacs para cancelación en sector primario requieren este archivo para cancelar. 
A través de openssl se puede crear el archivo usando: 
```bash
openssl pkcs12 -export -inkey keyfile.key.pem -in certfile.cer.pem -out file.pfx -passin pass:'password' --passout pass:'password'
```
Podría ser una buena opción agregar soporte para este tipo de archivos.

**Comment by eclipxe13** [comment]
Creo que hay que hacer pruebas con [`openssl_pkcs12_export`](https://www.php.net/openssl_pkcs12_export)

**Comment by celli33** [comment]
Cómo verías un método en [`PhpCfdi\Credentials\Credentials`](https://github.com/phpcfdi/credentials/blob/main/src/Credential.php) estilo: 
```php
public function pfx(): string
{
        // por implementar
}
```

**Comment by eclipxe13** [comment]
Creo que más bien podrían haber dos clases:
- `PfxExporter`, puede exportar a cadena de caracteres o a archivo local un objeto `Credential`.
- `PfxReader`, puede crear el objeto `Credential` a partir de una cadena de caracteres o un archivo local.

¿Qué opinas?
