### ISSUE TITLE
AYUDA CON FIRMA PFX

### ISSUE THREAD

**Issue by amolitos** [phpcfdi/credentials#19]
Que tal, soy muy nuevo en esto. Necesito firmar algunos documentos con mi efirma, pero la verdad estoy muy perdido. El SAT me entrego mi firma en formato `.pfx`, y al momento de hacer unas pruebas con esta librería obtengo el siguiente error:

`Fatal error: Uncaught UnexpectedValueException: Invalid PKCS#12 contents or wrong passphrase`

Mi código es: 

```
declare(strict_types=1);

use PhpCfdi\Credentials\Pfx\PfxReader;

$pfxReader = new PfxReader();
$keyname = "firma.pfx";
$passphrase = "#######";

$credential = $pfxReader->createCredentialFromContents(file_get_contents($keyname), $passphrase);
```

Ya verifiqué:

- La contraseña es la correcta.
- La ubicación del archivo firma es correcta.

No entiendo por qué falla, agradecería mucho la ayuda.

**Comment by eclipxe13** [comment]
El SAT entregó tu firma en PFX ?? Eso sí que no lo había escuchado!
Se supone que el lector de PFX funciona bien, así que, para confirmar:

1. cómo sabes que la contraseña es correcta?
2. `file_get_contents($keyname)` te devuelve el contenido de la llave?

También puedes extraer certificado y llave privada del archivo PFX, esta es una buena guía: https://www.ibm.com/docs/en/arl/9.7?topic=certification-extracting-certificate-keys-from-pfx-file

Creo que es más fácil ayudarte en Discord que a través de un issue. Te dejo la liga: https://discord.gg/aFGYXvX

ping @celli33 tienes alguna idea de por dónde podría ser el problema?
