### ISSUE TITLE
load Pkcs8 Key

### ISSUE THREAD

**Issue by eislasq** [phpcfdi/credentials#3]
Hola. Hace falta que el constructor de PrivateKey pueda cargar el contenido del archivo .key tal y como está para no tener que pasarlo primero a .pem

**Comment by eclipxe13** [comment]
¿cómo, solo con hacer un chunk con header/footer `ENCRYPTED PRIVATE KEY` (como en los certificados) lee la llave privada?

**Comment by eislasq** [comment]
Así es. Funciona.👍

**Comment by eislasq** [comment]
> ¿cómo, solo con hacer un chunk con header/footer `ENCRYPTED PRIVATE KEY` (como en los certificados) lee la llave privada?

Así es. Funciona 👍
