### ISSUE TITLE
Certificado Fiel o CSD

### ISSUE THREAD

**Issue by rkgarcia** [phpcfdi/credentials#7]
No sé si esto sea un issue pero saber si un certificado es fiel o no es posible a partir del purpose que es un arreglo en la posición [2][0] que es para que pueden ser usados dichos certificados.

Saludos.

**Comment by eclipxe13** [comment]
Lamentablemente no hay información "oficial" que indique cómo diferenciarlos.

Lo que no ha cambiado, es que el SAT ha emitido la FIEL/FEA *siempre* con el `subject.OU` vacío.
Y los CSD *siempre* con el `subject.OU` no vacío.
Por eso los identificamos así.

Si bien es cierto que los *purposes* del certificado son diferentes en el caso de la FIEL y los CSD, ¿cómo saber si esa es información confiable para diferenciarlos?

Si cuentan con información al respecto (técnica, oficial o algo parecido) con gusto la revisamos y si es necesario cambiamos la forma de identificación.

**Comment by eclipxe13** [comment]
Cierro este issue, si alguien encuentra información oficial o parecida que justifique la forma de diferenciar un CSD de una FIEL le pido por favor que nos la comparta y abra un nuevo issue. Gracias.
